[DRAFT] EECS 149 Lab Applications
icyphy/lf-buckler pull request #1
Opened 2022-05-20 21:45 UTC by gundralaa

LF adaptions of EECS 149 lab robot state machines for the buckler+nrf+romi platform.

2022-06-06 04:32 UTC, edwardalee requested changes
There is a problem with this PR. It shows every line of every file changed. I suspect this is a platform misconfiguration where, for example, the newline character has been changed. Git normally has no difficulty with variants of newline on different platforms, so this seems like a misconfiguration.

As I consequence, I cannot see what has changed.

2022-06-06 04:32 UTC, edwardalee commented on README.md
> +This set of instructions will guide a user on how to setup the EECS149 Lab VM to be able to use Lingua Franca. The installation requires sudo permissions on the vm.
Perhaps include a link to the Lab VM here?

2022-06-06 04:32 UTC, edwardalee commented on README.md
>  ## Install Cross-Compilation and Loading Tools
```suggestion
## Install Cross-Compilation and Loading Tools (Skip if using the Lab VM)
```

2022-06-06 04:32 UTC, edwardalee commented on README.md
> +This set of instructions will guide a user on how to setup the EECS149 Lab VM to be able to use Lingua Franca. The installation requires sudo permissions on the vm.
```suggestion
The easiest way to set up is to use the EECS 149 lab virtual machine.
This set of instructions will guide a user on how to setup the EECS149 Lab VM to be able to use Lingua Franca. The installation requires sudo permissions on the vm.
```

2022-07-12 01:32 UTC, lhstrh commented
Closing this PR to avoid confusion as it has been subsumed by https://github.com/icyphy/lf-buckler/pull/2.

2022-07-12 01:32 UTC, closed without merging