Temporary PR to reveal actual diff in #1
icyphy/lf-buckler pull request #2
Opened 2022-06-11 00:05 UTC by lhstrh

See https://github.com/icyphy/lf-buckler/pull/1.

2022-06-11 00:19 UTC, lsk567 commented
Thanks for taking a look at the diff issue! @lhstrh

2022-06-11 16:20 UTC, edwardalee requested changes
This looks great! However, there is a lot of code duplication among the .lf files.  Could you create one or more base classes, e.g. for the Robot, so that the code doesn't have to be repeated in each application? See https://www.lf-lang.org/docs/handbook/extending-reactors

2022-06-11 16:20 UTC, edwardalee commented on scripts/build_nrf_unix.sh
> +cp $PROJECT_ROOT/platform/lf_nRF52832_support.c $LF_SOURCE_GEN_DIRECTORY/include/core/platform/
Would it be better to create a symbolic link from include/core to core?

2022-06-11 16:20 UTC, edwardalee commented on src/KobukiBLE.lf
> +}
Add trailing newline?

2022-06-11 16:20 UTC, edwardalee commented on src/KobukiSensor.lf
> +}
Add trailing sensor?

2022-06-14 00:30 UTC, lhstrh commented on platform/lf_nrf52_support.h
> +<<<<<<< Updated upstream:platform/lf_nRF52832_support.h
Whoops?

2022-06-14 00:32 UTC, lhstrh commented on platform/lf_nrf52_support.h
> +=======
Conflict was not resolved (and I bet CRLF line endings were reintroduced)

2022-07-12 01:27 UTC, lhstrh reviewed
This is looking great, @gundralaa. I plan to toy with this tomorrow morning. Would you be available for help if I get stuck?

2022-07-12 01:27 UTC, lhstrh commented on scripts/ble_scripts/ble_utils.py
> +LAB11 = 0x02e0
```suggestion
LAB11 = 0x02e0

```

2022-07-12 01:27 UTC, lhstrh commented on scripts/ble_scripts/discover.py
> +asyncio.run(main())
```suggestion
asyncio.run(main())

```

2022-07-12 01:27 UTC, lhstrh commented on scripts/ble_scripts/led_writer.py
> +# TODO: Make sure these UUIDs match the ones in the LF files.
Could you elaborate on this `TODO`?

2022-07-12 01:27 UTC, lhstrh commented on src/KobukiBLE.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/KobukiSensor.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/KobukiSquare.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/KobukiSquareIMU.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/KobukiTemplate.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/ModalRomi.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/RobotInit.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/RomiTemplate/controller.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/RomiTemplate/main.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/SerialTest.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/SimpleBLE_adv.lf
> +}
```suggestion
}

```

2022-07-12 01:27 UTC, lhstrh commented on src/SimpleBLE_serv.lf
> +}
```suggestion
}

```

2022-07-29 13:42 UTC, merged